name: DC-Profiles
version: '${project.version}'
main: org.williamg.dcprofiles.DCProfiles
api-version: '1.21'
softdepend: [Vault, Luckperms, ChatEx]

commands:
  status:
    description: View profile and current name of specified player
    usage: /status <player>
  addnote:
    description: Adds note to a player's permanent record
    usage: /addnote <target player> <note>